[package]
name = "lockd"
version = "0.1.0"
authors = ["Kilobyte22 <stiepen22@gmx.de>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lockd-common = { path = "../common" }
anyhow = "1.0.100"
env_logger = "0.11.8"
futures = "0.3.31"
tokio = { version = "1.9.0", features = ["sync", "process", "rt", "macros", "fs", "signal"] }
tracing = "0.1.41"
zbus = { version = "5.11.0", features = ["tokio"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
libc = "0.2.176"
toml = "0.9.7"
serde = { version = "1.0.228", features = ["derive"] }
