//! # D-Bus interface proxy for: `de.kilobyte22.lockd.Manager`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `lockd.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "de.kilobyte22.lockd.Manager",
    default_service = "de.kilobyte22.lockd",
    default_path = "/de/kilobyte22/lockd"
)]
pub trait Manager {
    /// Lock method
    fn lock(&self, lockscreen: &str) -> zbus::Result<()>;

    /// Reload method
    fn reload(&self) -> zbus::Result<()>;

    /// LidSwitchInhibited property
    #[zbus(property)]
    fn lid_switch_inhibited(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_lid_switch_inhibited(&self, value: bool) -> zbus::Result<()>;

    /// Locked property
    #[zbus(property)]
    fn locked(&self) -> zbus::Result<bool>;
}
